name: Margiogram
options:
  bundleIdPrefix: com.margiovanni
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"
  xcodeVersion: "17.0"
  developmentLanguage: en
  defaultConfig: Debug
  groupSortPosition: top
  generateEmptyDirectories: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"
    SWIFT_STRICT_CONCURRENCY: complete
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_KEY_CFBundleDisplayName: Margiogram
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    GENERATE_INFOPLIST_FILE: "YES"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
    INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    SWIFT_EMIT_LOC_STRINGS: "YES"

configs:
  Debug:
    buildSettings:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      GCC_PREPROCESSOR_DEFINITIONS: "DEBUG=1 $(inherited)"
  Release:
    buildSettings:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_COMPILATION_MODE: wholemodule

targets:
  Margiogram:
    type: application
    platform: iOS
    sources:
      - path: Margiogram
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Margiogram/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.margiovanni.margiogram
        # Exclude arm64 from simulator to fix TDLibFramework crash on Apple Silicon
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
        INFOPLIST_KEY_UIStatusBarStyle: ""
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.social-networking"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "YES"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "YES"
        INFOPLIST_KEY_NSCameraUsageDescription: "Margiogram needs camera access for video calls and media capture"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Margiogram needs microphone access for voice messages and calls"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Margiogram needs photo library access to share media"
        INFOPLIST_KEY_NSContactsUsageDescription: "Margiogram needs contacts access to find your friends"
        INFOPLIST_KEY_NSFaceIDUsageDescription: "Margiogram uses Face ID for secure authentication"
    entitlements:
      path: Margiogram/Margiogram.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
    dependencies:
      - package: TDLibKit

  MargiogramMac:
    type: application
    platform: macOS
    sources:
      - path: Margiogram
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Margiogram/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.margiovanni.margiogram-mac
        CODE_SIGN_ENTITLEMENTS: Margiogram/MargiogramMac.entitlements
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.social-networking"
    entitlements:
      path: Margiogram/MargiogramMac.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true
    dependencies:
      - package: TDLibKit

  MargiogramTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MargiogramTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.margiovanni.margiogram.tests
    dependencies:
      - target: Margiogram

  MargiogramUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MargiogramUITests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.margiovanni.margiogram.uitests
    dependencies:
      - target: Margiogram

packages:
  TDLibKit:
    url: https://github.com/Swiftgram/TDLibKit
    exactVersion: "1.5.2-tdlib-1.8.53-bdec6af5"

schemes:
  Margiogram:
    build:
      targets:
        Margiogram: all
        MargiogramTests: [test]
        MargiogramUITests: [test]
    run:
      config: Debug
      environmentVariables:
        - variable: IDEPreferLogStreaming
          value: "YES"
          isEnabled: true
    test:
      config: Debug
      targets:
        - MargiogramTests
        - MargiogramUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  MargiogramMac:
    build:
      targets:
        MargiogramMac: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
